### ISSUE TITLE
SnapshotReader should read last Snapshot(as event) not first one

### ISSUE THREAD

**Issue by osoykan** [osoykan/ProductContext-EventSourcing#1]
https://github.com/osoykan/ProductContext-EventSourcing/blob/e8948b782c398ad6a8dacd1b839f9e596ce02587/lib/AggregateSource/src/EventStore.NetCore/AggregateSource.EventStore/Snapshots/AsyncSnapshotReader.cs#L69

**Comment by volak** [comment]
FYI you are actually reading the last event here.  You are reading the last single event from the stream
https://github.com/osoykan/ProductContext-EventSourcing/blob/e8948b782c398ad6a8dacd1b839f9e596ce02587/lib/AggregateSource/src/EventStore.NetCore/AggregateSource.EventStore/Snapshots/AsyncSnapshotReader.cs#L63

So returning `Events[0]` is returning the single last event of the stream as desired

👍 project

**Comment by osoykan** [comment]
@volak 

You are totally right, my oversight. Thank you for enlightenment and your comments.

**Comment by osoykan** [comment]
I'm closing this one, it is not an issue anymore:)
