### ISSUE TITLE
Unordered unthrottled event handling

### ISSUE THREAD

**Issue by Salgat** [osoykan/ProductContext-EventSourcing#2]
https://github.com/osoykan/ProductContext-EventSourcing/blob/master/src/ProductContext.Framework/ProjectionManager.cs#L76

The "SubscribeToAllFrom" supports an async event handler that respects ordering and blocking. The current use of an Action for an async method causes the subscription to feed the handler with events as fast as they come in and since these events are handled on tasks scheduled by the thread scheduler, there are no guarantees of the events being handled in order. An easy fix is to update the event handler to type

```
Func<EventStoreCatchUpSubscription, ResolvedEvent, Task> EventAppeared(
```

**Comment by osoykan** [comment]
Thanks a lot :) Fixed it.
